apiVersion: apps/v1
kind: Deployment
metadata:
   name: myweb-deploy
spec:
   replicas: 2
   selector:
      matchLabels:
         env: prod
   template:
     metadata:
       name: myweb-pod
       labels:
         env: prod
     spec:
       containers:
       - name: myweb-con
         image: khatrig/web1:v2
